# Generated by Django 3.0.5 on 2020-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
